---
dependency:
  name: galaxy
driver:
  name: docker

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        tlp_enable: false

platforms:
  - name: ansible-ubuntu-16-04
    image: ubuntu:16.04
  - name: ansible-ubuntu-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-18-10
    image: ubuntu:18.10
  - name: ansible-arch
    image: archimg/base
    image_version: full
    command: /lib/systemd/systemd
    privileged: true
  - name: ansible-fedora
    image: fedora
    image_version: latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
